hospital/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pacientes/' , include('pacientes.urls')),
    path('usuarios/' , include('usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pacientes/urls.py
from django.urls import path
from .views import Lista, Nuevo, Eliminar, Editar, buscar_municipio, Grafica_sangre, Grafica_edades, Lista_pacientes_pdf, Paciente_pdf
app_name = 'pacientes'

from .views import Vista_paciente_pdf
urlpatterns = [
    path('lista/', Lista.as_view(), name='lista'),
    path('nuevo/', Nuevo.as_view(), name='nuevo'),
    path('editar/<int:pk>', Editar.as_view(), name='editar'),
    path('eliminar/<int:pk>', Eliminar.as_view(), name='eliminar'),
    path('busca-municipio/', buscar_municipio, name='buscar_municipio'),
    path('grafica_edad/', Grafica_edades.as_view(), name='grafica_edades'),
    path('grafica_sangre/', Grafica_sangre.as_view(), name='grafica_sangre'),
    path('pdf/', Lista_pacientes_pdf.as_view(), name='pdf_pacientes'),
    path('paciente_pdf/<int:pk>', Vista_paciente_pdf.as_view(), name='paciente_pdf')

]

pacientes/models.py
from django.db import models


class Estado(models.Model):
    nombre = models.CharField('Nombre del estado',max_length=120)
    def __str__(self):
        return self.nombre
    

class Municipio(models.Model):
    nombre = models.CharField('Nombre del municipio',max_length=120)
    estado = models.ForeignKey(Estado, verbose_name="Estado", on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre


class Paciente(models.Model):
    TIPO_SANGRE =  [
        ('A+', 'A positivo'),
        ('A-', 'A negativo'),
        ('O+', 'O positivo'),
        ('O-', 'O negativo'),
    ]
    nombre = models.CharField(max_length=60)
    primerApellido = models.CharField('Apellido paterno',max_length=60)
    segundoApellido = models.CharField('Apellido materno', max_length=60, null=True, blank=True)
    numero_ss = models.CharField('Número de Seguro Social',max_length=20)
    fecha_nac = models.DateField('Fecha de nacimiento')
    tipo_sangre = models.CharField('Tipo de sangre', max_length=3, choices=TIPO_SANGRE)
    municipio = models.ForeignKey(Municipio, verbose_name='Municipio', on_delete=models.SET_NULL, null=True)
    estado = models.ForeignKey(Estado, verbose_name='Estado', on_delete=models.SET_NULL, null=True)


    def __str__(self):
        return self.nombre + ' ' + self.primerApellido
    

pacientes/forms.py
from .models import Paciente
from django.forms import ModelForm, TextInput, Select, DateInput


class PacienteForm(ModelForm):

    class Meta:
        model = Paciente
        fields = ('nombre','primerApellido','segundoApellido',
            'numero_ss','fecha_nac','tipo_sangre','estado','municipio')

        widgets = {
                'nombre':TextInput(attrs={'class':'form-control'}),
                'primerApellido':TextInput(attrs={'class':'form-control'}),
                'segundoApellido':TextInput(attrs={'class':'form-control'}),
                'numero_ss':TextInput(attrs={'class':'form-control'}),
                'fecha_nac':DateInput(attrs={'class':'form-control'}),
                'tipo_sangre':Select(attrs={'class':'form-control'}),
                'estado':Select(attrs={'class':'form-control'}),
                'municipio':Select(attrs={'class':'form-control'}),
        }

pacientes/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Paciente, Municipio, Estado
from .forms import PacienteForm
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.db.models import Count 
from django.db import models
from django.views.generic import TemplateView
from django.utils import  timezone
import datetime
from django_weasyprint import WeasyTemplateResponseMixin
from django.conf import settings
from django.views.generic.detail import DetailView
from django.views.generic import View

class Lista(ListView):

    paginate_by = 5 
    model = Paciente


class Nuevo(CreateView):
    model = Paciente
    form_class = PacienteForm
    
    success_url = reverse_lazy('pacientes:lista')

class Editar(UpdateView):
    model = Paciente
    form_class = PacienteForm
    extra_context = {'editar':True}

    success_url = reverse_lazy('pacientes:lista')

class Eliminar(DeleteView):
    model = Paciente
    success_url = reverse_lazy('pacientes:lista')


def buscar_municipio(request):
    id_estado = request.POST.get('id',None)
    if id_estado:
        municipios = Municipio.objects.filter(estado_id=id_estado)
        data = [{'id':mun.id,'nombre':mun.nombre} for mun in  municipios]
        return JsonResponse(data, safe=False)
    return JsonResponse({'error':'Parámetro inválido'}, safe=False)

class Grafica_sangre(TemplateView):
    template_name = 'pacientes/grafica_sangre.html'
    # todos los valores distintos de sangre contados por tipo
    pacientes_sangre = Paciente.objects.all().values('tipo_sangre').annotate(cuanto = Count('tipo_sangre'))
    # los tipos distintos de sangre que hay linea valida para mostrar solo los que se tienen
    #sangre_tipos = Paciente.objects.all().values('tipo_sangre').distinct()
   
    sangre_tipos = ['O+','O-', 'A-', 'A+']
    datos = []
     
    
    for sangre in sangre_tipos:
        cuantos = 0
        for tp in pacientes_sangre:
            #para cuando se cambia linea en sangre_tipos
            #if tp['tipo_sangre']==sangre['tipo_sangre']:
            if tp['tipo_sangre']== sangre:
                cuantos = tp['cuanto'] 
                break 
        datos.append({'name':tp['tipo_sangre'], 'data': [cuantos]})

    
    extra_context = {'datos': datos }
 

class Grafica_edades(TemplateView):

    template_name = 'pacientes/grafica_edad.html'
    # todos las edades con conteo por edad
    pacientes_edades = Paciente.objects.all().dates('fecha_nac','day').annotate(cuanto = Count('fecha_nac'))
    #pacientes_edades = Paciente.objects.raw( Select  * from   Paciente)
    # las distintas edades que tienen los pacientes
    edades = Paciente.objects.dates('fecha_nac','year')
   
    datos = []
    now = datetime.datetime.now()
    for edad in edades:
        cuantos = 0
        for ed in pacientes_edades:
            if ed.year== edad.year:
                cuantos = cuantos + 1
        datos.append({'name': (now.year - edad.year) , 'data': [cuantos]})

    
    extra_context = {'datos': datos}
 
class Vista_lista_pacientes_PDF(ListView):
    model = Paciente
    template_name = 'pacientes/lista_pacientes_PDF.html'
    #extra_context = {"suma": suma}

class Lista_pacientes_pdf(WeasyTemplateResponseMixin, Vista_lista_pacientes_PDF ):
    
    pdf_stylesheets =  [
        settings.STATICFILES_DIRS[0] + 'dist/css/adminlte.min.css',
        settings.STATICFILES_DIRS[0] + 'dist/css/estilos.css',
    ]
    pdf_attachment = False
    pdf_filename = 'pacientes_lista.pdf'


class Vista_paciente_pdf(CreateView):
    model = Paciente
    template_name = 'pacientes/paciente_pdf.html'
    form_class = PacienteForm
    extra_context = {'paciente_pdf':True}

class Paciente_pdf(WeasyTemplateResponseMixin, Vista_paciente_pdf):
    pdf_stylesheets =  [
        settings.STATICFILES_DIRS[0] + 'dist/css/adminlte.min.css',
        settings.STATICFILES_DIRS[0] + 'dist/css/estilos.css',
    ]
    pdf_attachment = False
    pdf_filename = 'paientes.pdf'

pacientes/templates/pacientes/grafica_edad.html
{% extends 'base.html' %}
{% block titulo %}
 Grafica Edades 
 {% endblock titulo %} 
 {% block contenido %} 


<div id="grafica" style="min-width: 310px; max-width: 800px; margin: 1em auto;"> </div>
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/exporting-data.js"></script>


<script>
	
    // Create the chart
    Highcharts.chart('grafica', {
    	lang:{
    		downloadCVS: "Descarga CVS",
    		downloadJPEG: "Descarga imagen JPEG",
    		downloadPDF: "Descarga PDF",
    		downloadPNG: "Descargar imagen PNG",
    		downloadSVG: "Descarga en imaen de verctores",
    		viewFullscreen: "Ver en pantalla completa",
    		printChart: "imprimir gráfica"
    	},
        chart: {
            type: 'column'
        },
        title: {
            text: 'Gráfica edades pacientes'
        },
        subtitle: {
            text: 'Pacientes agrupado edad'
        },

        xAxis: {
            categories: ['name']
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Cantidad de pacientes'
            }

        },

        plotOptions: {
            column: {
                pointPaddin: 0.2,
                borderWidth: 0
            }

        },

        series: {{datos | safe}}



    });
</script>

 {% endblock contenido %}

pacientes/templates/pacientes/grafica_sangre.html
{% extends 'base.html' %} 
{% load static %}
{% block titulo %} 
 Grafica Tipo Sangre 
{% endblock titulo %}
{% block contenido %}


<div id="grafica" style="min-width: 310px; max-width: 800px; margin: 1em auto;"> </div>
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/exporting-data.js"></script>


<script>
	
    // Create the chart
    Highcharts.chart('grafica', {
    	lang:{
    		downloadCVS: "Descarga CVS",
    		downloadJPEG: "Descarga imagen JPEG",
    		downloadPDF: "Descarga PDF",
    		downloadPNG: "Descargar imagen PNG",
    		downloadSVG: "Descarga en imaen de verctores",
    		viewFullscreen: "Ver en pantalla completa",
    		printChart: "imprimir gráfica"
    	},
        chart: {
            type: 'column'
        },
        title: {
            text: 'Gráfica tipo de sangre'
        },
        subtitle: {
            text: 'Pacientes agrupado por tipo de sangre'
        },

        xAxis: {
            categories: ['tipo_sangre']
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Cantidad de pacientes'
            }

        },

        plotOptions: {
            column: {
                pointPaddin: 0.2,
                borderWidth: 0
            }

        },

        series: {{datos | safe}}



    });
</script>

{% endblock contenido %}

pacientes/templates/pacientes/lista_pacientes_PDF.html
<h1>PDF de pacientes</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido paterno</th>
            <th>Apellido materno</th>
            <th>Fecha de nacimiento</th>
            <th>No. Seguro social</th>
            <th>Tipo de sangre</th>
        </tr>
    </thead>
    <tbody>
        {% for paciente in object_list %}
        <tr>
            <td>{{paciente.nombre}}</td>
            <td>{{paciente.primerApellido}}</td>
            <td>{{paciente.segundoApellido}}</td>
            <td>{{paciente.fecha_nac}}</td>
            <td>{{paciente.numero_ss}}</td>
            <td>{{paciente.tipo_sangre}}</td>
           
        </tr>
        {% endfor %}
    </tbody>
</table>

pacientes/templates/pacientes/paciente_confirm_delete.html
{% extends 'base.html' %}
{% block titulo %}
    Eliminar paciente
{% endblock titulo %}

{% block contenido %}

<form method="post">
    {% csrf_token %}
    <p>Quieres eliminar el paciente "{{ object }}"?</p>
    <input class="btn btn-danger" type="submit" value="Sí, si quiero">
    <a href="{% url 'pacientes:lista' %}" class="btn btn-secondary" >Mejor no</a>
</form>

{% endblock contenido %}

pacientes/templates/pacientes/paciente_form.html
{% extends 'base.html' %}

{% block titulo %}
    Agrega paciente
{% endblock titulo %}

{% block contenido %}
<div class="row">
    <div class="col-md-2"></div> 
    <div class="col-md-8">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                    {% if editar %}
                        Modificar paciente
                    {% else %}
                        Nuevo paciente
                    {% endif %}
                </h3>
            </div>
                <form method="post">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <div class="card-footer">
                        <input type="submit" class="btn btn-success" value="{% if editar %}Guardar cambios{% else %}Agregar{% endif %}">
                    </div>
                </form>
            </div>
        </div>
    </div> 
    <div class="col-md-2"></div> 

    {% endblock contenido %}
    
    

pacientes/templates/pacientes/paciente_list.html
{% extends 'base.html' %} {% block titulo %}Lista de pacientes{% endblock titulo %} {% block contenido %}
<h1>Lista de pacientes</h1>
<div class="card-footer">
    <a title="PDF lista " class="btn btn-danger" href="{% url 'pacientes:pdf_pacientes' %}">
        <i class="far fa-fax"></i>
    </a>
</div>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido paterno</th>
            <th>Apellido materno</th>
            <th>Fecha de nacimiento</th>
            <th>No. Seguro social</th>
            <th>Tipo de sangre</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        {% for paciente in object_list %}
        <tr>
            <td>{{paciente.nombre}}</td>
            <td>{{paciente.primerApellido}}</td>
            <td>{{paciente.segundoApellido}}</td>
            <td>{{paciente.fecha_nac}}</td>
            <td>{{paciente.numero_ss}}</td>
            <td>{{paciente.tipo_sangre}}</td>
            <td>
                <a title="PDF paciente" class="btn btn-warning" href="{% url 'pacientes:paciente_pdf' paciente.id %}">
                    <i class="far fa-fax"></i>
                </a>
                <a title="Actualiza paciente" class="btn btn-warning" href="{% url 'pacientes:editar' paciente.id %}">
                    <i class="far fa-edit"></i>
                </a>
                <a title="Elimina paciente" class="btn btn-danger" href="{% url 'pacientes:eliminar' paciente.id %}">
                    <i class="far fa-trash-alt"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span> -->


<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">

            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Anterior  </a>
        </li>
        {% endif %} {% for pagina in page_obj.paginator.page_range %} {% if page_obj.number == pagina%}
        <li class="page-item active"><a class="page-link" href="?page={{ pagina }}">{{pagina}}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ pagina }}">{{pagina}}</a></li>
        {% endif %} {% endfor %} {% if page_obj.has_next %}
        <li class="page-item">

            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
        </li>
        {% else %}
        <li class="page-item disabled">

            <a class="page-link" href="#" tabindex="-1">Siguiente</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endblock contenido %}

pacientes/templates/pacientes/paciente_pdf.html
{% extends 'base.html' %}

{% block titulo %}Lista de pacientes{% endblock titulo %}
    
{% block contenido %}
<div class="row">
    <div class="col-md-2"></div> 
    <div class="col-md-8">
        <div class="card card-primary">
            <div class="card-header">
            </div>
                <form method="post">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.description }}
                    </div>
                    
                </form>
        </div>
    </div>
</div> 
{% endblock contenido %}