hospital/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pacientes/' , include('pacientes.urls')),
    path('usuarios/' , include('usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from .views import Login, Nuevo, Perfil, ActivarCuenta
from django.contrib.auth.views import LogoutView


app_name = 'usuarios'

urlpatterns = [

    
    path('login/', Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('nuevo/', Nuevo.as_view(), name='nuevo'),
    path('perfil/<int:pk>', Perfil.as_view(), name='perfil'),
    path('activar/<slug:uidb64>/<slug:token>', ActivarCuenta.as_view(), name='activar'),
    
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User


class Usuario(User):
    rfc = models.CharField('R.F.C.', max_length=13)
    foto = models.ImageField('Foto', upload_to='perfil', blank=True, null=True)

    def __str__(self):
        return self.username
    

usuarios/forms.py
from django.forms import (ModelForm, PasswordInput, 
                CharField, TextInput, ValidationError)
from .models import Usuario
from django.contrib.auth.forms import AuthenticationForm

class UsuarioForm(ModelForm):
    password = CharField(widget=PasswordInput(
        attrs={'placeholder':'Escribe contraseña','class':'form-control'}), 
        label="Contraseña"
    )
    password_re = CharField(widget=PasswordInput(
        attrs={'placeholder':'Repite contraseña','class':'form-control'}), 
        label="Repita contraseña"
    )
    
    class Meta:
        model = Usuario
        fields = ('first_name','last_name','email','username','password','password_re')

        widgets = {
                'first_name':TextInput(attrs={'class':'form-control','placeholder':'Escribe tu nombre...'}),
                'email':TextInput(attrs={'class':'form-control','placeholder':'Escribe tu e-mail...'}),
                'last_name':TextInput(attrs={'class':'form-control','placeholder':'Escribe tus apellidos'}),
                'username':TextInput(attrs={'class':'form-control','placeholder':'Escribe tu nombre de usuario'}),
        }

    def save(self, commit=True):
        user = super(UsuarioForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    def clean_password(self,*args, **kwargs):
        if self.data['password'] != self.data['password_re']:
            raise ValidationError('Las contraseñas son diferentes')
        return self.data['password']


class PerfilForm(ModelForm):
    class Meta:
        model = Usuario
        fields = ('first_name','last_name','email','rfc','foto')



class LoginForm(AuthenticationForm):

    class Meta: 
        fields = '__all__'

        widgets = {
                
            'username':TextInput(attrs={'class':'form-control','placeholder':'Escribe tu nombre de usuario'}),
            'password':PasswordInput(attrs={'class':'form-control','placeholder':'Escribe tu contraseña...'}),
        }

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.forms import AuthenticationForm
from .forms import UsuarioForm, PerfilForm, LoginForm
from .models import Usuario
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import EmailMessage # para usar el gmail
from django.contrib.sites.shortcuts import get_current_site # para el dominio
from django.template.loader import render_to_string  # toma un html y lo pone como un string
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode # codififcar y decodificar en base 64
from django.utils.encoding import force_bytes, force_text
from .token import token_activacion 
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView
from django.contrib import messages

from django.db.models import Count


class Login(LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm


class Nuevo(CreateView):
    template_name = 'nuevo.html'
    model = Usuario
    form_class = UsuarioForm
    success_url = reverse_lazy('usuarios:login')

    def form_valid(self, form):
        usuario_form = UsuarioForm(self.request.POST, self.request.FILES)
        
        if usuario_form.is_valid():
            
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            current_site = get_current_site(self.request)
            dominio = get_current_site(self.request) #trae el dominio requiere importacion

            mensaje = render_to_string('confirmar_cuenta.html',
                {
                    'user': user,
                    'dominio': dominio,
                    'uid': urlsafe_base64_encode(force_bytes(user.id)),
                    'token': token_activacion.make_token(user)
                } # parametros que se mandan el html 
            )
            email = EmailMessage(
                'Activar cuenta', # asunto
                mensaje, 
                to=[user.email], # destinatario 
            ) # contenido del correo
            email.content_subtype = "html" ## para darle un formato o estilo al correo
            email.send()

        else:
            
            return self.render_to_response(self.get_context_data(form=form, extra_context = usuario_form))
        return super().form_valid(form)

             
class Perfil(SuccessMessageMixin, UpdateView):
    template_name = 'perfil.html'
    model = Usuario
    form_class = PerfilForm
    success_message = "El usuario %(first_name)s se actualizó con éxito"


    def get_success_url(self):
        pk = self.kwargs.get(self.pk_url_kwarg)
        url = reverse_lazy('usuarios:perfil', kwargs={'pk': pk})
        return url


class ActivarCuenta(TemplateView):
    

    def get(self, request, *args, ** kwargs):
        context = self.get_context_data(**kwargs)

        try:
            uid = urlsafe_base64_decode(kwargs['uidb64'])
            token = kwargs['token']
            user = Usuario.objects.get(pk = uid)
        except(TypeError, ValueError, Usuario.DoesNotExist):
            user = None
        
        if user is not None and token_activacion.check_token(user, token):
            user.is_active = True 
            user.save()
            
            messages.success(self.request, 'Cuenta activada, ingresar datos')
        else:
            messages.error(self.request, 'Token invalido, contacta al administrador ')

        return redirect('usuarios:login')

     

usuarios/templates/confirmar_cuenta.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmar cuenta</title>
</head>

<body>
    <div>
        <h3>Validar cuenta</h3>
        <p>
            Hola <b>{{user.username}}.</b>

        </p>
        <p> Para completar tu registro en el Hospital debes de dar click en el siguietne enlace:</p>
        <br>
        <br>
        <p>
            <a href="http://{{dominio}}{% url "usuarios:activar" uidb64=uid token=token %}"> Activar cuenta </a> </p>
        <p><i>Saludos!!!</i></p>
    </div>
</body>

</html>

usuarios/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login Hospital</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <!-- <link rel="stylesheet" href="{% static 'https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' %}"> -->
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>Admin</b>LTE</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Iniciar sesión</p>

                {% if form.errors %}
                <div class="alert alert-warning">
                    Datos no válidos, verifica tu información
                </div>
                {% endif %} {% if mensaje %} {% for message in messages %}
                <div class="alert alert-{% if message.tags == 'error' %} warning {% else %} success {% endif %}">
                    {{message}}
                </div>
                {% endfor %} {% endif %}
                <form method="post">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <input required type="text" name="username" class="form-control" placeholder="Nombre de usuario">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input required type="password" name="password" class="form-control" placeholder="Contraseña">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-8">
                            <div class="icheck-primary">
                                <input type="checkbox" id="remember">
                                <label for="remember">
                Rercordar usuario
              </label>
                            </div>
                        </div>
                        <!-- /.col -->
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Ingresar</button>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>


                <p class="mb-1">
                    <a href="forgot-password.html">Olvide mi contraseña</a>
                </p>
                <p class="mb-0">
                    <a href="{% url 'usuarios:nuevo' %}" class="text-center">Registrar</a>
                </p>
            </div>
            <!-- /.login-card-body -->
        </div>
    </div>
    <!-- /.login-box -->

    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>

</body>

</html>

usuarios/templates/nuevo.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Registro Hospital</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <a href="../../index2.html"><b>Hospital Matasanos</a>
  </div>

  <div class="card">
    <div class="card-body register-card-body">
      <p class="login-box-msg">Registro de usuarios</p>

      <form method="post">
          {% csrf_token %}
        {{form.as_p}}
        <div class="row">
            <div class="col-8">
              <div class="icheck-primary">
                <input type="checkbox" id="agreeTerms" name="terms" value="agree">
                <label for="agreeTerms">
                <a href="">Estoy de acuerdo con los terminos</a>
                </label>
              </div>
            </div>
            <!-- /.col -->
            <div class="col-4">
              <button type="submit" class="btn btn-primary btn-block">Registrar</button>
            </div>
            <!-- /.col -->
          </div>
      </form>

      <a href="{% url 'usuarios:login' %}" class="text-center">Ya tengo una cuenta</a>
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
<!-- /.register-box -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
</body>
</html>

usuarios/templates/perfil.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    Modifica perfil de usuario
{% endblock titulo %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
{% endblock css %}

{% block contenido %}
<div class="row">
    <div class="col-md-2"></div> 
    <div class="col-md-8">
        {{mensaje}}
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                   Actualiza perfil
                </h3>
            </div>
                
                <form method="post" enctype="multipart/form-data">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <div class="card-footer">
                        <input type="submit" class="btn btn-success" value="Actualizar datos">
                    </div>
                </form>
            </div>
        </div>
    </div> 
    <div class="col-md-2"></div> 

    {% endblock contenido %}
    
    
    {% block scripts %}
        
      
        {% if messages %}
        <script src="{% static 'plugins/sweetalert2/sweetalert2.min.js' %}"></script>
        <!-- Toastr -->
        <script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
            <script type="text/javascript">
                var mensaje = '';
                {% for message in messages %}
                    mensaje += '{{message}}';
                {% endfor %}
                
                    const Toast = Swal.mixin({
                        toast: true,
                        position: 'top-end',
                        showConfirmButton: false,
                        timer: 3000
                    });
            
                    Toast.fire({
                        type: 'success',
                        title: mensaje
                    });
               
            </script>
        {% endif %}
    {% endblock scripts %}
        
    